version: 2

updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: monthly
          time: '01:00'
          timezone: America/New_York
      open-pull-requests-limit: 99
