---

- repo: local
  hooks:
  - id: sync_versions
    name: sync versions of additional_dependencies in .pre-commit-hooks.yaml
    language: script
    entry: ./sync_versions.sh
    files: ^package.json$
