---
- id: shfmt
  name: shfmt
  description: Shell source code formatter
  language: golang
  additional_dependencies:
      - mvdan.cc/sh/v3/cmd/shfmt@v3.4.2
  entry: shfmt
  args:
      - -i # use spaces for indents
      - '4'
      - -ci # indent switch cases
      - -sr # redirect operators are followed by space
      - -bn # binary ops like && or | (pipe) start the line
  types: [shell]

- id: eslint
  name: eslint
  language: node
  entry: eslint --fix --cache --no-ignore

  types:
      - file
  files: (\.(js|ts)$|(^|/)package\.json$)
  additional_dependencies:
      - '@stylistic/eslint-plugin@5.10.0' # sync:yarn.lock
      - '@typescript-eslint/eslint-plugin@8.63.0' # sync:yarn.lock
      - '@typescript-eslint/parser@8.63.0' # sync:yarn.lock
      - 'eslint@10.6.0' # sync:yarn.lock
      - 'eslint-config-prettier@10.1.8' # sync:yarn.lock
      - 'eslint-plugin-no-only-tests@3.4.0' # sync:yarn.lock
      - 'eslint-plugin-package-json@1.5.0' # sync:yarn.lock
      - 'eslint-plugin-prettier@5.5.6' # sync:yarn.lock
      - 'eslint-plugin-simple-import-sort@13.0.0' # sync:yarn.lock
      - 'import-modules@3.2.0' # sync:yarn.lock
      - 'jsonc-eslint-parser@3.1.0' # sync:yarn.lock
      - 'typescript-eslint@8.63.0' # sync:yarn.lock
      - 'prettier@3.9.4' # sync:yarn.lock
      - 'typescript@6.0.3' # sync:yarn.lock
