---

- id: shfmt
  name: shfmt
  description: Shell source code formatter
  language: golang
  additional_dependencies:
    - mvdan.cc/sh/v3/cmd/shfmt@v3.4.2
  entry: shfmt
  args:
    - -i # use spaces for indents
    - '4'
    - -ci # indent switch cases
    - -sr # redirect operators are followed by space
    - -bn # binary ops like && or | (pipe) start the line
  types: [shell]

- id: eslint
  name: eslint
  language: node
  entry: eslint
  args: [--fix, --cache, --ext, ".ts,.js", --no-ignore]
  types: [file]
  files: \.(js|ts)$
  additional_dependencies:
    - "@typescript-eslint/eslint-plugin@5.10.0"
    - "@typescript-eslint/parser@5.10.0"
    - "eslint@8.7.0"
    - "eslint-config-prettier@8.3.0"
    - "eslint-plugin-es@4.1.0"
    - "eslint-plugin-no-only-tests@2.6.0"
    - "eslint-plugin-prettier@4.0.0"
    - "eslint-plugin-simple-import-sort@7.0.0"
    - "import-modules@2.1.0"
    - "prettier@2.5.1"
    - "typescript@4.5.4"
