---
- id: shfmt
  name: shfmt
  description: Shell source code formatter
  language: golang
  additional_dependencies:
      - mvdan.cc/sh/v3/cmd/shfmt@v3.4.2
  entry: shfmt
  args:
      - -i # use spaces for indents
      - '4'
      - -ci # indent switch cases
      - -sr # redirect operators are followed by space
      - -bn # binary ops like && or | (pipe) start the line
  types: [shell]

- id: eslint
  name: eslint
  language: node
  entry: eslint --fix --cache --ext '.ts,.js' --no-ignore
  types:
      - file
  files: \.(js|ts)$
  additional_dependencies:
      - '@typescript-eslint/eslint-plugin@5.20.0' # sync:yarn.lock
      - '@typescript-eslint/parser@5.20.0' # sync:yarn.lock
      - 'eslint@8.13.0' # sync:yarn.lock
      - 'eslint-config-prettier@8.5.0' # sync:yarn.lock
      - 'eslint-plugin-import@2.26.0' # sync:yarn.lock
      - 'eslint-plugin-es@4.1.0' # sync:yarn.lock
      - 'eslint-plugin-no-only-tests@2.6.0' # sync:yarn.lock
      - 'eslint-plugin-prettier@4.0.0' # sync:yarn.lock
      - 'eslint-plugin-simple-import-sort@7.0.0' # sync:yarn.lock
      - 'import-modules@3.1.0' # sync:yarn.lock
      - 'prettier@2.6.2' # sync:yarn.lock
      - 'typescript@4.6.3' # sync:yarn.lock
