---

- id: shfmt
  name: shfmt
  description: Shell source code formatter
  language: golang
  additional_dependencies:
    - mvdan.cc/sh/v3/cmd/shfmt@v3.4.2
  entry: shfmt
  args:
    - -i # use spaces for indents
    - '4'
    - -ci # indent switch cases
    - -sr # redirect operators are followed by space
    - -bn # binary ops like && or | (pipe) start the line
  types: [shell]

- id: eslint
  name: eslint
  language: node
  entry: eslint --fix --cache --ext '.ts,.js' --no-ignore
  types:
    - file
  files: \.(js|ts)$
  additional_dependencies:
    - "@typescript-eslint/eslint-plugin@5.10.2" # sync:package.json
    - "@typescript-eslint/parser@5.10.2" # sync:package.json
    - "eslint@8.8.0" # sync:package.json
    - "eslint-config-prettier@8.3.0" # sync:package.json
    - "eslint-plugin-es@4.1.0" # sync:package.json
    - "eslint-plugin-no-only-tests@2.6.0" # sync:package.json
    - "eslint-plugin-prettier@4.0.0" # sync:package.json
    - "eslint-plugin-simple-import-sort@7.0.0" # sync:package.json
    - "import-modules@2.1.0" # sync:package.json
    - "prettier@2.5.1" # sync:package.json
    - "typescript@4.5.5" # sync:package.json

- id: sync_versions
  name: sync versions of additional_dependencies in .pre-commit-hooks.yaml
  language: script
  entry: ./sync_versions.sh
  files: ^package.json$
